### PR TITLE
Improved regexes

### PR DESCRIPTION
**Pull request by billinghamj**
Valid outcodes must start with a letter.

https://en.wikipedia.org/wiki/Postcodes_in_the_United_Kingdom#Validation

### CODE REVIEW

**Comment by billinghamj** [comment]
This and #4 probably can't both be merged automatically because they change code on adjacent lines.

**Comment by cblanc** [comment]
Thats ok, I'll square it on my end.

**Comment by billinghamj** [comment]
@cblanc Rebased this onto master. So can now be merged

**Comment by billinghamj** [comment]
@cblanc Thanks! Could you push to npm please?

**Comment by cblanc** [comment]
[0.2.4 is on npm](https://www.npmjs.com/package/postcode)

Thanks once more for the PRs (-:

**Comment by billinghamj** [comment]
No worries. Thanks for pushing :)

**Pull request merged**
